import CategorySelector from "@/components/CategorySelector";
import SortingSelector from "@/components/SortingSelector";
import type { Metadata } from "next";
import { getCategories } from "@/app/services/getCategories";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function StoreLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const data = await getCategories();

  return (
    <div className="flex justify-center flex-col items-center">
      <section className="w-[90%] mx-auto mt-10  py-3 px-2   flex gap-2 items-center justify-around shadow-lg  ">
        <CategorySelector data={data} />
        <SortingSelector />
      </section>

      {children}
    </div>
  );
}
