import type { Metadata } from "next";
import "./globals.css";
import StoreHeader from "@/components/StoreHeader";
import Footer from "@/components/Footer";
import SnowfallEffect from "../components/SnowfallEffect";
import { Montserrat } from "next/font/google";

const montserrat = Montserrat({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` antialiased overflow-x-hidden ${montserrat.className}`}
      >
        <StoreHeader />

        <main className="relative">
          {/* <SnowfallEffect /> */}
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
